<?php
			$optionsArray = array( 'totals' => array( 'fab_id' => array( 'totalsType' => '' ),
'id_ente' => array( 'totalsType' => '' ),
'id_d_area' => array( 'totalsType' => '' ),
'd1_id' => array( 'totalsType' => '' ),
'med_specialisti' => array( 'totalsType' => '' ),
'medspecialisti_appr' => array( 'totalsType' => '' ),
'd1_stato' => array( 'totalsType' => '' ),
'd2_id' => array( 'totalsType' => '' ),
'medici' => array( 'totalsType' => '' ),
'medici_appr' => array( 'totalsType' => '' ),
'd2_stato' => array( 'totalsType' => '' ),
'd3_id' => array( 'totalsType' => '' ),
'infermieri' => array( 'totalsType' => '' ),
'infermieri_appr' => array( 'totalsType' => '' ),
'd3_stato' => array( 'totalsType' => '' ),
'd4_id' => array( 'totalsType' => '' ),
'specializandi' => array( 'totalsType' => '' ),
'specializzandi_appr' => array( 'totalsType' => '' ),
'd4_stato' => array( 'totalsType' => '' ),
'd5_id' => array( 'totalsType' => '' ),
'altri' => array( 'totalsType' => '' ),
'altri_appr' => array( 'totalsType' => '' ),
'd5_stato' => array( 'totalsType' => '' ),
'data_richiesta' => array( 'totalsType' => '' ),
'nome' => array( 'totalsType' => '' ),
'minimo_posti_rich' => array( 'totalsType' => '' ),
'nome1' => array( 'totalsType' => '' ),
'fab_stato_id' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fab_id',
'id_ente',
'id_d_area',
'd1_id',
'd1_stato',
'd2_id',
'medici',
'medici_appr',
'd2_stato',
'd3_id',
'infermieri',
'infermieri_appr',
'd3_stato',
'd4_id',
'specializandi',
'specializzandi_appr',
'd4_stato',
'd5_id',
'altri',
'altri_appr',
'd5_stato',
'data_richiesta',
'nome',
'nome1',
'minimo_posti_rich',
'fab_stato_id' ),
'exportFields' => array( 'fab_id',
'id_ente',
'id_d_area',
'd1_id',
'd1_stato',
'd2_id',
'medici',
'medici_appr',
'd2_stato',
'd3_id',
'infermieri',
'infermieri_appr',
'd3_stato',
'd4_id',
'specializandi',
'specializzandi_appr',
'd4_stato',
'd5_id',
'altri',
'altri_appr',
'd5_stato',
'data_richiesta',
'nome',
'nome1',
'minimo_posti_rich',
'fab_stato_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fab_id' => array( 'export_field' ),
'id_ente' => array( 'export_field1' ),
'id_d_area' => array( 'export_field2' ),
'd1_id' => array( 'export_field3' ),
'd1_stato' => array( 'export_field6' ),
'd2_id' => array( 'export_field7' ),
'medici' => array( 'export_field8' ),
'medici_appr' => array( 'export_field9' ),
'd2_stato' => array( 'export_field10' ),
'd3_id' => array( 'export_field11' ),
'infermieri' => array( 'export_field12' ),
'infermieri_appr' => array( 'export_field13' ),
'd3_stato' => array( 'export_field14' ),
'd4_id' => array( 'export_field15' ),
'specializandi' => array( 'export_field16' ),
'specializzandi_appr' => array( 'export_field17' ),
'd4_stato' => array( 'export_field18' ),
'd5_id' => array( 'export_field19' ),
'altri' => array( 'export_field20' ),
'altri_appr' => array( 'export_field21' ),
'd5_stato' => array( 'export_field22' ),
'data_richiesta' => array( 'export_field23' ),
'nome' => array( 'export_field24' ),
'nome1' => array( 'export_field25' ),
'minimo_posti_rich' => array( 'export_field26' ),
'fab_stato_id' => array( 'export_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'fab_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'id_ente',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'id_d_area',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'd1_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'd1_stato',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'd2_id',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'medici',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'medici_appr',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'd2_stato',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'd3_id',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'infermieri',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'infermieri_appr',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'd3_stato',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'd4_id',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'specializandi',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'specializzandi_appr',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'd4_stato',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'd5_id',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'altri',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'altri_appr',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'd5_stato',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'data_richiesta',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'nome',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'nome1',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'minimo_posti_rich',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'fab_stato_id',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>