<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'fab_id',
'id_ente',
'id_d_area',
'd1_id',
'med_specialisti',
'medspecialisti_appr',
'd1_stato',
'd2_id',
'medici',
'medici_appr',
'd2_stato',
'd3_id',
'infermieri',
'infermieri_appr',
'd3_stato',
'd4_id',
'specializandi',
'specializzandi_appr',
'd4_stato',
'd5_id',
'altri',
'altri_appr',
'd5_stato',
'data_richiesta',
'nome',
'nome1',
'minimo_posti_rich',
'fab_stato_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fab_id' => array( 'integrated_search_field' ),
'id_ente' => array( 'integrated_search_field1' ),
'id_d_area' => array( 'integrated_search_field2' ),
'd1_id' => array( 'integrated_search_field3' ),
'med_specialisti' => array( 'integrated_search_field4' ),
'medspecialisti_appr' => array( 'integrated_search_field5' ),
'd1_stato' => array( 'integrated_search_field6' ),
'd2_id' => array( 'integrated_search_field7' ),
'medici' => array( 'integrated_search_field8' ),
'medici_appr' => array( 'integrated_search_field9' ),
'd2_stato' => array( 'integrated_search_field10' ),
'd3_id' => array( 'integrated_search_field11' ),
'infermieri' => array( 'integrated_search_field12' ),
'infermieri_appr' => array( 'integrated_search_field13' ),
'd3_stato' => array( 'integrated_search_field14' ),
'd4_id' => array( 'integrated_search_field15' ),
'specializandi' => array( 'integrated_search_field16' ),
'specializzandi_appr' => array( 'integrated_search_field17' ),
'd4_stato' => array( 'integrated_search_field18' ),
'd5_id' => array( 'integrated_search_field19' ),
'altri' => array( 'integrated_search_field20' ),
'altri_appr' => array( 'integrated_search_field21' ),
'd5_stato' => array( 'integrated_search_field22' ),
'data_richiesta' => array( 'integrated_search_field23' ),
'nome' => array( 'integrated_search_field24' ),
'nome1' => array( 'integrated_search_field25' ),
'minimo_posti_rich' => array( 'integrated_search_field26' ),
'fab_stato_id' => array( 'integrated_search_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'fab_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'id_ente',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'id_d_area',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'd1_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'med_specialisti',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'medspecialisti_appr',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'd1_stato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'd2_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'medici',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'medici_appr',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'd2_stato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'd3_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'infermieri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'infermieri_appr',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'd3_stato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'd4_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'specializandi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'specializzandi_appr',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'd4_stato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'd5_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'altri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'altri_appr',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'd5_stato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'data_richiesta',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'nome',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'nome1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'minimo_posti_rich',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'fab_stato_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>