<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_covidhr_t_fabbisogno  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, &$pageObject)
{

		global  $conn;
// DE Verifico se l'utente è abilitato ad entrare
$sql_login="select  id_profilo  from r_utente_profilo where id_profilo = 7 and cf_utente='" . $_SESSION['utente'] ."'";

$rs_data=pg_query($conn,$sql_login);
$row=pg_fetch_row($rs_data);

if ($row[0]==7)
return true;
else
{
     die("Utente non abilitato all'applicativo ");
     return false;
}


;		
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
